- name: this playbook will create the vpc in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: this playbook will create the vpc in aws
      ec2_vpc_net:
        name: "vpc_name"
        region: "region"
        cidr_block: "vpccidr"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcout
    - debug:
        var: vpcout

    - name:
      ec2_vpc_subnet:
        name: "{{pubsub1cidr}}"
        region: "{{region}"
        cidr_block: "{{}}"
        az: "{{pub1subcidr}}"
